/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface LazyImage {
    /**
    * This attribute defines the alternative text describing the image. Users will see this text displayed if the image URL is wrong, the image is not in one of the supported formats, or if the image is not yet downloaded.
    */
    'alt'?: string;
    /**
    * Defines the distance from the viewport that the image will load
    */
    'rootMargin'?: string;
    /**
    * The image URL. This attribute is mandatory for the `<img>` element.
    */
    'src'?: string;
  }
}

declare global {


  interface HTMLLazyImageElement extends Components.LazyImage, HTMLStencilElement {}
  var HTMLLazyImageElement: {
    prototype: HTMLLazyImageElement;
    new (): HTMLLazyImageElement;
  };
  interface HTMLElementTagNameMap {
    'lazy-image': HTMLLazyImageElement;
  }
}

declare namespace LocalJSX {
  interface LazyImage {
    /**
    * This attribute defines the alternative text describing the image. Users will see this text displayed if the image URL is wrong, the image is not in one of the supported formats, or if the image is not yet downloaded.
    */
    'alt'?: string;
    /**
    * Emitted when the image has finished loading
    */
    'onLazyImgDidLoad'?: (event: CustomEvent<void>) => void;
    /**
    * Emitted when the img fails to load
    */
    'onLazyImgError'?: (event: CustomEvent<void>) => void;
    /**
    * Emitted when the img src has been set
    */
    'onLazyImgWillLoad'?: (event: CustomEvent<void>) => void;
    /**
    * Defines the distance from the viewport that the image will load
    */
    'rootMargin'?: string;
    /**
    * The image URL. This attribute is mandatory for the `<img>` element.
    */
    'src'?: string;
  }

  interface IntrinsicElements {
    'lazy-image': LazyImage;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'lazy-image': LocalJSX.LazyImage & JSXBase.HTMLAttributes<HTMLLazyImageElement>;
    }
  }
}


